#ifndef GENERATED 
#define GENERATED 
 
char* AssetsFolderStructure[] { 
"Abilities/",
"Ability/",
"Ability/Active/",
"Ability/Active/textures/",
"Ability/Support/",
"Ability/Support/textures/",
"BounceAnim/",
"Bullet/",
"DropTables/",
"Enemies/",
"Enemies/Atom/",
"Enemies/Gaspra/",
"Enemies/MarsTwo/",
"EngineResources/",
"Entity Definitions/",
"Fonts/",
"Fonts/OpenSans/",
"Fonts/Rajdhani/",
"Gears/",
"Gears/textures/",
"Items/",
"Materials/",
"Missions/",
"Monsters/",
"Monsters/BowlBoy/",
"Monsters/Legion/",
"Monsters/medical_assistant/",
"Monsters/medical_assistant/textures/",
"Monsters/mining_laser/",
"Monsters/mining_laser/textures/",
"Monsters/orca_supply/",
"Monsters/orca_supply/textures/",
"Monsters/Para/",
"Monsters/Pill/",
"Monsters/replicator/",
"Monsters/replicator/replicator_1/",
"Monsters/replicator/replicator_2/",
"Monsters/replicator/replicator_3/",
"Monsters/replicator/replicator_4/",
"Monsters/replicator/replicator_5/",
"Monsters/replicator/textures/",
"Monsters/spark_shock/",
"Monsters/spark_shock/textures/",
"Monsters/SpikeBall/",
"Monsters/SpikeBall/Textures/",
"Monsters/stun_damage/",
"Monsters/stun_damage/textures/",
"Monsters/taunt_helper/",
"Monsters/taunt_helper/textures/",
"MonsterShards/",
"MonsterShards/Common/",
"MonsterShards/Common/textures/",
"MonsterShards/Epic/",
"MonsterShards/Epic/textures/",
"MonsterShards/Legendary/",
"MonsterShards/Legendary/textures/",
"MonsterShards/Rare/",
"MonsterShards/Rare/textures/",
"OverviewShips/",
"OverviewShips/Cube/",
"PBRBall/",
"PlayerEntity/",
"Rooms/",
"Shaders/",
"Skybox/",
"Skybox/space/",
"StatusEffects/",
"Stone/",
"Tests/",
"Trainer/",
"Trainer/textures/",
}; 

string glsl_type_NAME[] { 
"none",
"gl_mat4",
"gl_vec4",
"gl_vec3",
"gl_vec2",
"gl_sampler2D",
"gl_bool",
"gl_samplerCube",
"gl_float",
"gl_int",
}; 



 #endif 
